<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_cuisine_cancel_first_option</name>
   <tag></tag>
   <elementGuidId>dc65492a-d962-4514-a112-a96f6fc654f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='repeat-filterdetails-container_default']/div[2]/div/div[2]/span/span[1]/span/ul/li[1]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
