<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_openstatus_cancel_first_option</name>
   <tag></tag>
   <elementGuidId>290ae259-9a68-4769-b2c9-70b6a391b9bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='repeat-filterdetails-container_default']/div[1]/div/div[2]/span/span[1]/span/ul/li[1]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
