<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_meal_type_2</name>
   <tag></tag>
   <elementGuidId>fdd5edec-d030-404d-91f3-fbeb6f92a506</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//*[@id='repeat-filterdetails-container_add']/div[1]/div/div[2]/span/span[1]/span/ul</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
