<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cuisine</name>
   <tag></tag>
   <elementGuidId>bc52c2c6-dd42-49a4-9614-14de9e4b3a95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//*[@id='repeat-filterdetails-container_default']/div[2]/div/div[2]/span/span[1]/span/ul</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
