<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_meal_type_3</name>
   <tag></tag>
   <elementGuidId>8cbff2e8-1b9b-4e05-9b08-bddee5957ba2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//*[@id='repeat-filterdetails-container_add']/div[2]/div/div[2]/span/span[1]/span/ul</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
