<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msg_error_meal_type_time</name>
   <tag></tag>
   <elementGuidId>2c50ee85-00d3-4d76-a91b-0174bc8842da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'Please fill empty meal type and times' or . = 'Please fill empty meal type and times')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-pnotify-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-role</name>
      <type>Main</type>
      <value>alert</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please fill empty meal type and times</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;body_Class  navbar-top analytics_module&quot;]/div[@class=&quot;ui-pnotify bg-success ui-pnotify-fade-normal ui-pnotify-mobile-able ui-pnotify-move ui-pnotify-in ui-pnotify-fade-in&quot;]/div[@class=&quot;brighttheme ui-pnotify-container brighttheme-notice ui-pnotify-shadow&quot;]/div[@class=&quot;ui-pnotify-text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
