<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Promotions</name>
   <tag></tag>
   <elementGuidId>f4deb462-924a-4b44-8215-0d8b789f030b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://his-uat.digivalet.com/cms/promotions</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Promotions</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_navigation_sidebar&quot;)/div[@class=&quot;sidebar-category sidebar-category-visible&quot;]/div[@class=&quot;category-content no-padding&quot;]/ul[@class=&quot;navigation navigation-main navigation-accordion&quot;]/li[3]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
