<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Restaurants</name>
   <tag></tag>
   <elementGuidId>03401321-0370-4bc4-9f8f-28183843f61a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://his-uat.digivalet.com/cms/restaurant</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Restaurants</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_navigation_sidebar&quot;)/div[@class=&quot;sidebar-category sidebar-category-visible&quot;]/div[@class=&quot;category-content no-padding&quot;]/ul[@class=&quot;navigation navigation-main navigation-accordion&quot;]/li[7]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
